# Sub-Queries

In [ ]:

ðŸ”¥ where can be subqueries be used ?
-select
-from
-having
-insert
-update
-delete

In [ ]:
select * from cust
where id in
(select id from cust
where salary > 4500);

select name ,
(votes/(select sum(votes) from movies))*100 as per_of_votes
from movies;

select name,genre,score,
(select avg(score)  from movies m2
where m2.genre=m1.genre) as avg_score
from movies m1
order by avg_score desc limit 1;

select genre , avg_rating
from (select rating , avg(score) as 'avg_rating'
from movies
group by rating ) t1 join movies;

select genre, avg(score)
from movies
group by genre
having avg(score) > (select avg(score) from movies);

update cust_tables
set salary =salary*10
where age in (select age from cust_tables
where age =35);